# Generated by Django 5.0.6 on 2025-05-21 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='android_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='battery_level',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='device_model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
